# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/Fresh/Device.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2
from Devialet.Fresh import UpdateImage_pb2 as Devialet_dot_Fresh_dot_UpdateImage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/Fresh/Device.proto',
  package='Devialet.Fresh',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x44\x65vialet/Fresh/Device.proto\x12\x0e\x44\x65vialet.Fresh\x1a\x1bgoogle/protobuf/empty.proto\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\x1a Devialet/Fresh/UpdateImage.proto\"A\n\x13InstallationProcess\x12*\n\x05image\x18\x01 \x01(\x0b\x32\x1b.Devialet.Fresh.UpdateImage\"\x89\x04\n\x10\x44\x65viceProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12<\n\x05state\x18\x02 \x01(\x0e\x32&.Devialet.Fresh.DeviceProperties.StateB\x05\xda>\x02\x18\x01\x12\x38\n\x0c\x63urrentImage\x18\x03 \x01(\x0b\x32\x1b.Devialet.Fresh.UpdateImageB\x05\xda>\x02 \x01\x12\x38\n\x0c\x64\x65siredImage\x18\x04 \x01(\x0b\x32\x1b.Devialet.Fresh.UpdateImageB\x05\xda>\x02\x18\x01\x12\x39\n\rpreparedImage\x18\x05 \x01(\x0b\x32\x1b.Devialet.Fresh.UpdateImageB\x05\xda>\x02\x18\x01\x12G\n\x13installationProcess\x18\x06 \x01(\x0b\x32#.Devialet.Fresh.InstallationProcessB\x05\xda>\x02\x18\x01\x12<\n\x10lastSkippedImage\x18\x07 \x01(\x0b\x32\x1b.Devialet.Fresh.UpdateImageB\x05\xda>\x02\x18\x01\"F\n\x05State\x12\x0b\n\x07Unknown\x10\x00\x12\x0c\n\x08UpToDate\x10\x01\x12\x12\n\x0eReadyForUpdate\x10\x02\x12\x0e\n\nNeedUpdate\x10\x03\x32\xf6\x01\n\x06\x44\x65vice\x12\x37\n\x05\x63heck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12@\n\x0e\x66inalizeUpdate\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x42\n\x04skip\x12\x1b.Devialet.Fresh.UpdateImage\x1a\x16.google.protobuf.Empty\"\x05\xc2>\x02(\x01\x1a-\xc2>*\x08\x01\x1a\x14io.dvlt.fresh.device\"\x10\x44\x65vicePropertiesb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,Devialet_dot_Fresh_dot_UpdateImage__pb2.DESCRIPTOR,])



_DEVICEPROPERTIES_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='Devialet.Fresh.DeviceProperties.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UpToDate', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ReadyForUpdate', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NeedUpdate', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=714,
  serialized_end=784,
)
_sym_db.RegisterEnumDescriptor(_DEVICEPROPERTIES_STATE)


_INSTALLATIONPROCESS = _descriptor.Descriptor(
  name='InstallationProcess',
  full_name='Devialet.Fresh.InstallationProcess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='Devialet.Fresh.InstallationProcess.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=260,
)


_DEVICEPROPERTIES = _descriptor.Descriptor(
  name='DeviceProperties',
  full_name='Devialet.Fresh.DeviceProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.Fresh.DeviceProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='Devialet.Fresh.DeviceProperties.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentImage', full_name='Devialet.Fresh.DeviceProperties.currentImage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002 \001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desiredImage', full_name='Devialet.Fresh.DeviceProperties.desiredImage', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preparedImage', full_name='Devialet.Fresh.DeviceProperties.preparedImage', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='installationProcess', full_name='Devialet.Fresh.DeviceProperties.installationProcess', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastSkippedImage', full_name='Devialet.Fresh.DeviceProperties.lastSkippedImage', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DEVICEPROPERTIES_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=784,
)

_INSTALLATIONPROCESS.fields_by_name['image'].message_type = Devialet_dot_Fresh_dot_UpdateImage__pb2._UPDATEIMAGE
_DEVICEPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_DEVICEPROPERTIES.fields_by_name['state'].enum_type = _DEVICEPROPERTIES_STATE
_DEVICEPROPERTIES.fields_by_name['currentImage'].message_type = Devialet_dot_Fresh_dot_UpdateImage__pb2._UPDATEIMAGE
_DEVICEPROPERTIES.fields_by_name['desiredImage'].message_type = Devialet_dot_Fresh_dot_UpdateImage__pb2._UPDATEIMAGE
_DEVICEPROPERTIES.fields_by_name['preparedImage'].message_type = Devialet_dot_Fresh_dot_UpdateImage__pb2._UPDATEIMAGE
_DEVICEPROPERTIES.fields_by_name['installationProcess'].message_type = _INSTALLATIONPROCESS
_DEVICEPROPERTIES.fields_by_name['lastSkippedImage'].message_type = Devialet_dot_Fresh_dot_UpdateImage__pb2._UPDATEIMAGE
_DEVICEPROPERTIES_STATE.containing_type = _DEVICEPROPERTIES
DESCRIPTOR.message_types_by_name['InstallationProcess'] = _INSTALLATIONPROCESS
DESCRIPTOR.message_types_by_name['DeviceProperties'] = _DEVICEPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstallationProcess = _reflection.GeneratedProtocolMessageType('InstallationProcess', (_message.Message,), dict(
  DESCRIPTOR = _INSTALLATIONPROCESS,
  __module__ = 'Devialet.Fresh.Device_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.Fresh.InstallationProcess)
  ))
_sym_db.RegisterMessage(InstallationProcess)

DeviceProperties = _reflection.GeneratedProtocolMessageType('DeviceProperties', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEPROPERTIES,
  __module__ = 'Devialet.Fresh.Device_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.Fresh.DeviceProperties)
  ))
_sym_db.RegisterMessage(DeviceProperties)


_DEVICEPROPERTIES.fields_by_name['state']._options = None
_DEVICEPROPERTIES.fields_by_name['currentImage']._options = None
_DEVICEPROPERTIES.fields_by_name['desiredImage']._options = None
_DEVICEPROPERTIES.fields_by_name['preparedImage']._options = None
_DEVICEPROPERTIES.fields_by_name['installationProcess']._options = None
_DEVICEPROPERTIES.fields_by_name['lastSkippedImage']._options = None

_DEVICE = _descriptor.ServiceDescriptor(
  name='Device',
  full_name='Devialet.Fresh.Device',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>*\010\001\032\024io.dvlt.fresh.device\"\020DeviceProperties'),
  serialized_start=787,
  serialized_end=1033,
  methods=[
  _descriptor.MethodDescriptor(
    name='check',
    full_name='Devialet.Fresh.Device.check',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finalizeUpdate',
    full_name='Devialet.Fresh.Device.finalizeUpdate',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='skip',
    full_name='Devialet.Fresh.Device.skip',
    index=2,
    containing_service=None,
    input_type=Devialet_dot_Fresh_dot_UpdateImage__pb2._UPDATEIMAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=_b('\302>\002(\001'),
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICE)

DESCRIPTOR.services_by_name['Device'] = _DEVICE

# @@protoc_insertion_point(module_scope)
