# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/Fresh/UpdateImage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/Fresh/UpdateImage.proto',
  package='Devialet.Fresh',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n Devialet/Fresh/UpdateImage.proto\x12\x0e\x44\x65vialet.Fresh\"\x8d\x04\n\x0bUpdateImage\x12\x13\n\x0bmajorUpdate\x18\x01 \x01(\x08\x12\x11\n\toutOfDate\x18\x02 \x01(\x08\x12\x13\n\x0bproductType\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\x12\x13\n\x0b\x66romVersion\x18\x05 \x01(\t\x12\x11\n\ttoVersion\x18\x06 \x01(\t\x12\x0b\n\x03url\x18\x07 \x01(\t\x12\x10\n\x08\x66ileHash\x18\x08 \x01(\t\x12\x14\n\x0c\x63hangelogUrl\x18\t \x01(\t\x12\x17\n\x0f\x66romFullVersion\x18\x0e \x01(\t\x12\x15\n\rtoFullVersion\x18\x0f \x01(\t\x12<\n\x0brequirement\x18\n \x01(\x0e\x32\'.Devialet.Fresh.UpdateImage.Requirement\x12;\n\x08metadata\x18\x0b \x03(\x0b\x32).Devialet.Fresh.UpdateImage.MetadataEntry\x12\x19\n\x11isRequiredAtSetup\x18\x0c \x01(\x08\x12\x10\n\x08isForced\x18\r \x01(\x08\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"O\n\x0bRequirement\x12\x0b\n\x07Unknown\x10\x00\x12\x0c\n\x08Optional\x10\x01\x12\x0c\n\x08Required\x10\x02\x12\x17\n\x13RequiredImmediately\x10\x03\x62\x06proto3')
)



_UPDATEIMAGE_REQUIREMENT = _descriptor.EnumDescriptor(
  name='Requirement',
  full_name='Devialet.Fresh.UpdateImage.Requirement',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Optional', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Required', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RequiredImmediately', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=499,
  serialized_end=578,
)
_sym_db.RegisterEnumDescriptor(_UPDATEIMAGE_REQUIREMENT)


_UPDATEIMAGE_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='Devialet.Fresh.UpdateImage.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Devialet.Fresh.UpdateImage.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.Fresh.UpdateImage.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=497,
)

_UPDATEIMAGE = _descriptor.Descriptor(
  name='UpdateImage',
  full_name='Devialet.Fresh.UpdateImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='majorUpdate', full_name='Devialet.Fresh.UpdateImage.majorUpdate', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outOfDate', full_name='Devialet.Fresh.UpdateImage.outOfDate', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productType', full_name='Devialet.Fresh.UpdateImage.productType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='Devialet.Fresh.UpdateImage.id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromVersion', full_name='Devialet.Fresh.UpdateImage.fromVersion', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toVersion', full_name='Devialet.Fresh.UpdateImage.toVersion', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='Devialet.Fresh.UpdateImage.url', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileHash', full_name='Devialet.Fresh.UpdateImage.fileHash', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='changelogUrl', full_name='Devialet.Fresh.UpdateImage.changelogUrl', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromFullVersion', full_name='Devialet.Fresh.UpdateImage.fromFullVersion', index=9,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toFullVersion', full_name='Devialet.Fresh.UpdateImage.toFullVersion', index=10,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requirement', full_name='Devialet.Fresh.UpdateImage.requirement', index=11,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='Devialet.Fresh.UpdateImage.metadata', index=12,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isRequiredAtSetup', full_name='Devialet.Fresh.UpdateImage.isRequiredAtSetup', index=13,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isForced', full_name='Devialet.Fresh.UpdateImage.isForced', index=14,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UPDATEIMAGE_METADATAENTRY, ],
  enum_types=[
    _UPDATEIMAGE_REQUIREMENT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=578,
)

_UPDATEIMAGE_METADATAENTRY.containing_type = _UPDATEIMAGE
_UPDATEIMAGE.fields_by_name['requirement'].enum_type = _UPDATEIMAGE_REQUIREMENT
_UPDATEIMAGE.fields_by_name['metadata'].message_type = _UPDATEIMAGE_METADATAENTRY
_UPDATEIMAGE_REQUIREMENT.containing_type = _UPDATEIMAGE
DESCRIPTOR.message_types_by_name['UpdateImage'] = _UPDATEIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateImage = _reflection.GeneratedProtocolMessageType('UpdateImage', (_message.Message,), dict(

  MetadataEntry = _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), dict(
    DESCRIPTOR = _UPDATEIMAGE_METADATAENTRY,
    __module__ = 'Devialet.Fresh.UpdateImage_pb2'
    # @@protoc_insertion_point(class_scope:Devialet.Fresh.UpdateImage.MetadataEntry)
    ))
  ,
  DESCRIPTOR = _UPDATEIMAGE,
  __module__ = 'Devialet.Fresh.UpdateImage_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.Fresh.UpdateImage)
  ))
_sym_db.RegisterMessage(UpdateImage)
_sym_db.RegisterMessage(UpdateImage.MetadataEntry)


_UPDATEIMAGE_METADATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
