# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RendererNode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import DefaultMessages_pb2 as Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2
import EntityNode_pb2 as EntityNode__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RendererNode.proto',
  package='Devialet.MasterOfPuppets',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12RendererNode.proto\x12\x18\x44\x65vialet.MasterOfPuppets\x1a\x1bgoogle/protobuf/empty.proto\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a*Devialet/CallMeMaybe/DefaultMessages.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\x1a\x10\x45ntityNode.proto\"G\n\x0cGroupMessage\x12$\n\x02id\x18\x01 \x01(\x0b\x32\x18.Devialet.CallMeMaybe.Id\x12\x11\n\tisDefault\x18\x02 \x01(\x08\"\x8f\x01\n\x16RendererNodeProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12:\n\x05group\x18\x02 \x01(\x0b\x32&.Devialet.MasterOfPuppets.GroupMessageB\x03\xda>\x00\x32\xaf\x01\n\x0cRendererNode\x12P\n\x17identificationRequested\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x05\xc2>\x02\x18\x01\x1aM\xc2>J\x08\x01\x12#Devialet.MasterOfPuppets.EntityNode\x1a\t.renderer\"\x16RendererNodePropertiesb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,EntityNode__pb2.DESCRIPTOR,])




_GROUPMESSAGE = _descriptor.Descriptor(
  name='GroupMessage',
  full_name='Devialet.MasterOfPuppets.GroupMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Devialet.MasterOfPuppets.GroupMessage.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isDefault', full_name='Devialet.MasterOfPuppets.GroupMessage.isDefault', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=295,
)


_RENDERERNODEPROPERTIES = _descriptor.Descriptor(
  name='RendererNodeProperties',
  full_name='Devialet.MasterOfPuppets.RendererNodeProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.MasterOfPuppets.RendererNodeProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group', full_name='Devialet.MasterOfPuppets.RendererNodeProperties.group', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\000'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=441,
)

_GROUPMESSAGE.fields_by_name['id'].message_type = Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2._ID
_RENDERERNODEPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_RENDERERNODEPROPERTIES.fields_by_name['group'].message_type = _GROUPMESSAGE
DESCRIPTOR.message_types_by_name['GroupMessage'] = _GROUPMESSAGE
DESCRIPTOR.message_types_by_name['RendererNodeProperties'] = _RENDERERNODEPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GroupMessage = _reflection.GeneratedProtocolMessageType('GroupMessage', (_message.Message,), dict(
  DESCRIPTOR = _GROUPMESSAGE,
  __module__ = 'RendererNode_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.MasterOfPuppets.GroupMessage)
  ))
_sym_db.RegisterMessage(GroupMessage)

RendererNodeProperties = _reflection.GeneratedProtocolMessageType('RendererNodeProperties', (_message.Message,), dict(
  DESCRIPTOR = _RENDERERNODEPROPERTIES,
  __module__ = 'RendererNode_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.MasterOfPuppets.RendererNodeProperties)
  ))
_sym_db.RegisterMessage(RendererNodeProperties)


_RENDERERNODEPROPERTIES.fields_by_name['group']._options = None

_RENDERERNODE = _descriptor.ServiceDescriptor(
  name='RendererNode',
  full_name='Devialet.MasterOfPuppets.RendererNode',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>J\010\001\022#Devialet.MasterOfPuppets.EntityNode\032\t.renderer\"\026RendererNodeProperties'),
  serialized_start=444,
  serialized_end=619,
  methods=[
  _descriptor.MethodDescriptor(
    name='identificationRequested',
    full_name='Devialet.MasterOfPuppets.RendererNode.identificationRequested',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=_b('\302>\002\030\001'),
  ),
])
_sym_db.RegisterServiceDescriptor(_RENDERERNODE)

DESCRIPTOR.services_by_name['RendererNode'] = _RENDERERNODE

# @@protoc_insertion_point(module_scope)
