# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SourcesIndex.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import DefaultMessages_pb2 as Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SourcesIndex.proto',
  package='Devialet.MotherOfAllSources',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12SourcesIndex.proto\x12\x1b\x44\x65vialet.MotherOfAllSources\x1a\x1bgoogle/protobuf/empty.proto\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a*Devialet/CallMeMaybe/DefaultMessages.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\"J\n\x10SourceIdentifier\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x06system\x18\x02 \x01(\x0b\x32\x18.Devialet.CallMeMaybe.Id\"\x9a\x01\n\x11SourceInformation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tisStarted\x18\x02 \x01(\x08\x12\x41\n\x04type\x18\x03 \x01(\x0e\x32\x33.Devialet.MotherOfAllSources.SourceInformation.Type\"!\n\x04Type\x12\x0c\n\x08Physical\x10\x00\x12\x0b\n\x07Virtual\x10\x01\"\xcb\x01\n\x15SourceIndexProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12\x46\n\x07sources\x18\x02 \x03(\x0b\x32..Devialet.MotherOfAllSources.SourceInformationB\x05\xda>\x02\x18\x01\x12/\n\x06system\x18\x03 \x01(\x0b\x32\x18.Devialet.CallMeMaybe.IdB\x05\xda>\x02\x18\x01\x32\xf5\x04\n\x0cSourcesIndex\x12N\n\x05start\x12-.Devialet.MotherOfAllSources.SourceIdentifier\x1a\x16.google.protobuf.Empty\x12M\n\x04stop\x12-.Devialet.MotherOfAllSources.SourceIdentifier\x1a\x16.google.protobuf.Empty\x12]\n\rsourceStarted\x12-.Devialet.MotherOfAllSources.SourceIdentifier\x1a\x16.google.protobuf.Empty\"\x05\xc2>\x02\x18\x01\x12]\n\rsourceStopped\x12-.Devialet.MotherOfAllSources.SourceIdentifier\x1a\x16.google.protobuf.Empty\"\x05\xc2>\x02\x18\x01\x12\x63\n\x13sourceStartTimedOut\x12-.Devialet.MotherOfAllSources.SourceIdentifier\x1a\x16.google.protobuf.Empty\"\x05\xc2>\x02\x18\x01\x12\x62\n\x12sourceStopTimedOut\x12-.Devialet.MotherOfAllSources.SourceIdentifier\x1a\x16.google.protobuf.Empty\"\x05\xc2>\x02\x18\x01\x1a?\xc2><\x08\x01\x1a!io.dvlt.motherofallsources.daemon\"\x15SourceIndexPropertiesb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,])



_SOURCEINFORMATION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Devialet.MotherOfAllSources.SourceInformation.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Physical', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Virtual', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=407,
  serialized_end=440,
)
_sym_db.RegisterEnumDescriptor(_SOURCEINFORMATION_TYPE)


_SOURCEIDENTIFIER = _descriptor.Descriptor(
  name='SourceIdentifier',
  full_name='Devialet.MotherOfAllSources.SourceIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Devialet.MotherOfAllSources.SourceIdentifier.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='system', full_name='Devialet.MotherOfAllSources.SourceIdentifier.system', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=283,
)


_SOURCEINFORMATION = _descriptor.Descriptor(
  name='SourceInformation',
  full_name='Devialet.MotherOfAllSources.SourceInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Devialet.MotherOfAllSources.SourceInformation.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isStarted', full_name='Devialet.MotherOfAllSources.SourceInformation.isStarted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.MotherOfAllSources.SourceInformation.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOURCEINFORMATION_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=440,
)


_SOURCEINDEXPROPERTIES = _descriptor.Descriptor(
  name='SourceIndexProperties',
  full_name='Devialet.MotherOfAllSources.SourceIndexProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.MotherOfAllSources.SourceIndexProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sources', full_name='Devialet.MotherOfAllSources.SourceIndexProperties.sources', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='system', full_name='Devialet.MotherOfAllSources.SourceIndexProperties.system', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=646,
)

_SOURCEIDENTIFIER.fields_by_name['system'].message_type = Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2._ID
_SOURCEINFORMATION.fields_by_name['type'].enum_type = _SOURCEINFORMATION_TYPE
_SOURCEINFORMATION_TYPE.containing_type = _SOURCEINFORMATION
_SOURCEINDEXPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_SOURCEINDEXPROPERTIES.fields_by_name['sources'].message_type = _SOURCEINFORMATION
_SOURCEINDEXPROPERTIES.fields_by_name['system'].message_type = Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2._ID
DESCRIPTOR.message_types_by_name['SourceIdentifier'] = _SOURCEIDENTIFIER
DESCRIPTOR.message_types_by_name['SourceInformation'] = _SOURCEINFORMATION
DESCRIPTOR.message_types_by_name['SourceIndexProperties'] = _SOURCEINDEXPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SourceIdentifier = _reflection.GeneratedProtocolMessageType('SourceIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _SOURCEIDENTIFIER,
  __module__ = 'SourcesIndex_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.MotherOfAllSources.SourceIdentifier)
  ))
_sym_db.RegisterMessage(SourceIdentifier)

SourceInformation = _reflection.GeneratedProtocolMessageType('SourceInformation', (_message.Message,), dict(
  DESCRIPTOR = _SOURCEINFORMATION,
  __module__ = 'SourcesIndex_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.MotherOfAllSources.SourceInformation)
  ))
_sym_db.RegisterMessage(SourceInformation)

SourceIndexProperties = _reflection.GeneratedProtocolMessageType('SourceIndexProperties', (_message.Message,), dict(
  DESCRIPTOR = _SOURCEINDEXPROPERTIES,
  __module__ = 'SourcesIndex_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.MotherOfAllSources.SourceIndexProperties)
  ))
_sym_db.RegisterMessage(SourceIndexProperties)


_SOURCEINDEXPROPERTIES.fields_by_name['sources']._options = None
_SOURCEINDEXPROPERTIES.fields_by_name['system']._options = None

_SOURCESINDEX = _descriptor.ServiceDescriptor(
  name='SourcesIndex',
  full_name='Devialet.MotherOfAllSources.SourcesIndex',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302><\010\001\032!io.dvlt.motherofallsources.daemon\"\025SourceIndexProperties'),
  serialized_start=649,
  serialized_end=1278,
  methods=[
  _descriptor.MethodDescriptor(
    name='start',
    full_name='Devialet.MotherOfAllSources.SourcesIndex.start',
    index=0,
    containing_service=None,
    input_type=_SOURCEIDENTIFIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stop',
    full_name='Devialet.MotherOfAllSources.SourcesIndex.stop',
    index=1,
    containing_service=None,
    input_type=_SOURCEIDENTIFIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sourceStarted',
    full_name='Devialet.MotherOfAllSources.SourcesIndex.sourceStarted',
    index=2,
    containing_service=None,
    input_type=_SOURCEIDENTIFIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=_b('\302>\002\030\001'),
  ),
  _descriptor.MethodDescriptor(
    name='sourceStopped',
    full_name='Devialet.MotherOfAllSources.SourcesIndex.sourceStopped',
    index=3,
    containing_service=None,
    input_type=_SOURCEIDENTIFIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=_b('\302>\002\030\001'),
  ),
  _descriptor.MethodDescriptor(
    name='sourceStartTimedOut',
    full_name='Devialet.MotherOfAllSources.SourcesIndex.sourceStartTimedOut',
    index=4,
    containing_service=None,
    input_type=_SOURCEIDENTIFIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=_b('\302>\002\030\001'),
  ),
  _descriptor.MethodDescriptor(
    name='sourceStopTimedOut',
    full_name='Devialet.MotherOfAllSources.SourcesIndex.sourceStopTimedOut',
    index=5,
    containing_service=None,
    input_type=_SOURCEIDENTIFIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=_b('\302>\002\030\001'),
  ),
])
_sym_db.RegisterServiceDescriptor(_SOURCESINDEX)

DESCRIPTOR.services_by_name['SourcesIndex'] = _SOURCESINDEX

# @@protoc_insertion_point(module_scope)
