# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TheMagicKey.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TheMagicKey.proto',
  package='Devialet.TheMagicKey',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11TheMagicKey.proto\x12\x14\x44\x65vialet.TheMagicKey\x1a\x1bgoogle/protobuf/empty.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\"p\n\x07Request\x12\x17\n\x08serverId\x18\x01 \x02(\x0c\x42\x05\xca>\x02\x08\x01\x12\x11\n\tserviceId\x18\x02 \x02(\x07\x12\x18\n\trequestId\x18\x03 \x02(\x0c\x42\x05\xca>\x02\x08\x01\x12\x0c\n\x04type\x18\x04 \x02(\r\x12\x11\n\tsubTypeId\x18\x05 \x02(\r\"\x96\x01\n\x05Reply\x12\x17\n\x08serverId\x18\x01 \x02(\x0c\x42\x05\xca>\x02\x08\x01\x12\x11\n\tserviceId\x18\x02 \x02(\x07\x12\x18\n\trequestId\x18\x03 \x02(\x0c\x42\x05\xca>\x02\x08\x01\x12\x0c\n\x04type\x18\x04 \x02(\r\x12\x11\n\tsubTypeId\x18\x05 \x02(\r\x12\x11\n\terrorCode\x18\x06 \x02(\x11\x12\x13\n\x0bisMultipart\x18\x07 \x02(\x08\"$\n\x11\x43onnectionRequest\x12\x0f\n\x07version\x18\x01 \x02(\r\"#\n\x07Service\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x02(\t\"[\n\x0f\x43onnectionReply\x12\x17\n\x08serverId\x18\x01 \x02(\x0c\x42\x05\xca>\x02\x08\x01\x12/\n\x08services\x18\x02 \x03(\x0b\x32\x1d.Devialet.TheMagicKey.Service\"\"\n\x12\x41uthenticationBlob\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"I\n\x18SetAuthorizedKeysRequest\x12\x11\n\tsignature\x18\x01 \x02(\x0c\x12\x1a\n\x12\x61uthorizedKeysData\x18\x02 \x02(\x0c\"#\n\x0eGenericRequest\x12\x11\n\tsignature\x18\x01 \x02(\x0c')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Devialet.TheMagicKey.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='Devialet.TheMagicKey.Request.serverId', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\312>\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceId', full_name='Devialet.TheMagicKey.Request.serviceId', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='Devialet.TheMagicKey.Request.requestId', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\312>\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.TheMagicKey.Request.type', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subTypeId', full_name='Devialet.TheMagicKey.Request.subTypeId', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=229,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='Devialet.TheMagicKey.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='Devialet.TheMagicKey.Reply.serverId', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\312>\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceId', full_name='Devialet.TheMagicKey.Reply.serviceId', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='Devialet.TheMagicKey.Reply.requestId', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\312>\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.TheMagicKey.Reply.type', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subTypeId', full_name='Devialet.TheMagicKey.Reply.subTypeId', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='Devialet.TheMagicKey.Reply.errorCode', index=5,
      number=6, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isMultipart', full_name='Devialet.TheMagicKey.Reply.isMultipart', index=6,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=382,
)


_CONNECTIONREQUEST = _descriptor.Descriptor(
  name='ConnectionRequest',
  full_name='Devialet.TheMagicKey.ConnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Devialet.TheMagicKey.ConnectionRequest.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=420,
)


_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='Devialet.TheMagicKey.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Devialet.TheMagicKey.Service.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Devialet.TheMagicKey.Service.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=457,
)


_CONNECTIONREPLY = _descriptor.Descriptor(
  name='ConnectionReply',
  full_name='Devialet.TheMagicKey.ConnectionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='Devialet.TheMagicKey.ConnectionReply.serverId', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\312>\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='services', full_name='Devialet.TheMagicKey.ConnectionReply.services', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=550,
)


_AUTHENTICATIONBLOB = _descriptor.Descriptor(
  name='AuthenticationBlob',
  full_name='Devialet.TheMagicKey.AuthenticationBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Devialet.TheMagicKey.AuthenticationBlob.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=586,
)


_SETAUTHORIZEDKEYSREQUEST = _descriptor.Descriptor(
  name='SetAuthorizedKeysRequest',
  full_name='Devialet.TheMagicKey.SetAuthorizedKeysRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='Devialet.TheMagicKey.SetAuthorizedKeysRequest.signature', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authorizedKeysData', full_name='Devialet.TheMagicKey.SetAuthorizedKeysRequest.authorizedKeysData', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=588,
  serialized_end=661,
)


_GENERICREQUEST = _descriptor.Descriptor(
  name='GenericRequest',
  full_name='Devialet.TheMagicKey.GenericRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='Devialet.TheMagicKey.GenericRequest.signature', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=698,
)

_CONNECTIONREPLY.fields_by_name['services'].message_type = _SERVICE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['ConnectionRequest'] = _CONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['ConnectionReply'] = _CONNECTIONREPLY
DESCRIPTOR.message_types_by_name['AuthenticationBlob'] = _AUTHENTICATIONBLOB
DESCRIPTOR.message_types_by_name['SetAuthorizedKeysRequest'] = _SETAUTHORIZEDKEYSREQUEST
DESCRIPTOR.message_types_by_name['GenericRequest'] = _GENERICREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'TheMagicKey_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TheMagicKey.Request)
  ))
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'TheMagicKey_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TheMagicKey.Reply)
  ))
_sym_db.RegisterMessage(Reply)

ConnectionRequest = _reflection.GeneratedProtocolMessageType('ConnectionRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONREQUEST,
  __module__ = 'TheMagicKey_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TheMagicKey.ConnectionRequest)
  ))
_sym_db.RegisterMessage(ConnectionRequest)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), dict(
  DESCRIPTOR = _SERVICE,
  __module__ = 'TheMagicKey_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TheMagicKey.Service)
  ))
_sym_db.RegisterMessage(Service)

ConnectionReply = _reflection.GeneratedProtocolMessageType('ConnectionReply', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONREPLY,
  __module__ = 'TheMagicKey_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TheMagicKey.ConnectionReply)
  ))
_sym_db.RegisterMessage(ConnectionReply)

AuthenticationBlob = _reflection.GeneratedProtocolMessageType('AuthenticationBlob', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATIONBLOB,
  __module__ = 'TheMagicKey_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TheMagicKey.AuthenticationBlob)
  ))
_sym_db.RegisterMessage(AuthenticationBlob)

SetAuthorizedKeysRequest = _reflection.GeneratedProtocolMessageType('SetAuthorizedKeysRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETAUTHORIZEDKEYSREQUEST,
  __module__ = 'TheMagicKey_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TheMagicKey.SetAuthorizedKeysRequest)
  ))
_sym_db.RegisterMessage(SetAuthorizedKeysRequest)

GenericRequest = _reflection.GeneratedProtocolMessageType('GenericRequest', (_message.Message,), dict(
  DESCRIPTOR = _GENERICREQUEST,
  __module__ = 'TheMagicKey_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TheMagicKey.GenericRequest)
  ))
_sym_db.RegisterMessage(GenericRequest)


_REQUEST.fields_by_name['serverId']._options = None
_REQUEST.fields_by_name['requestId']._options = None
_REPLY.fields_by_name['serverId']._options = None
_REPLY.fields_by_name['requestId']._options = None
_CONNECTIONREPLY.fields_by_name['serverId']._options = None
# @@protoc_insertion_point(module_scope)
