# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/IMASlave4U/Configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/IMASlave4U/Configuration.proto',
  package='Devialet.IMASlave4U',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'Devialet/IMASlave4U/Configuration.proto\x12\x13\x44\x65vialet.IMASlave4U\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\"\xcb\x01\n\x0bRoleMessage\x12\x33\n\x04role\x18\x01 \x01(\x0e\x32%.Devialet.IMASlave4U.RoleMessage.Role\"\x86\x01\n\x04Role\x12\x0b\n\x07Unknown\x10\x00\x12\n\n\x06\x43ustom\x10\x01\x12\x0f\n\x0b\x46rontCenter\x10\x02\x12\r\n\tFrontLeft\x10\x03\x12\x0e\n\nFrontRight\x10\x04\x12\x0e\n\nRearCenter\x10\x05\x12\x0c\n\x08RearLeft\x10\x06\x12\r\n\tRearRight\x10\x07\x12\x08\n\x04Mono\x10\x08\"\xaf\x01\n\x17\x43onfigurationProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12.\n\x04role\x18\x02 \x01(\x0b\x32 .Devialet.IMASlave4U.RoleMessage\x12\x14\n\x0cvolumeOffset\x18\x03 \x01(\r\x12\x13\n\x0bvolumeLimit\x18\x04 \x01(\r2Q\n\rConfiguration\x1a@\xc2>=\x08\x01\x1a io.dvlt.imaslave4u.configuration\"\x17\x43onfigurationPropertiesb\x06proto3')
  ,
  dependencies=[Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,])



_ROLEMESSAGE_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='Devialet.IMASlave4U.RoleMessage.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Custom', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FrontCenter', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FrontLeft', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FrontRight', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RearCenter', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RearLeft', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RearRight', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Mono', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=219,
  serialized_end=353,
)
_sym_db.RegisterEnumDescriptor(_ROLEMESSAGE_ROLE)


_ROLEMESSAGE = _descriptor.Descriptor(
  name='RoleMessage',
  full_name='Devialet.IMASlave4U.RoleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='Devialet.IMASlave4U.RoleMessage.role', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROLEMESSAGE_ROLE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=353,
)


_CONFIGURATIONPROPERTIES = _descriptor.Descriptor(
  name='ConfigurationProperties',
  full_name='Devialet.IMASlave4U.ConfigurationProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.IMASlave4U.ConfigurationProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='Devialet.IMASlave4U.ConfigurationProperties.role', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volumeOffset', full_name='Devialet.IMASlave4U.ConfigurationProperties.volumeOffset', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volumeLimit', full_name='Devialet.IMASlave4U.ConfigurationProperties.volumeLimit', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=531,
)

_ROLEMESSAGE.fields_by_name['role'].enum_type = _ROLEMESSAGE_ROLE
_ROLEMESSAGE_ROLE.containing_type = _ROLEMESSAGE
_CONFIGURATIONPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_CONFIGURATIONPROPERTIES.fields_by_name['role'].message_type = _ROLEMESSAGE
DESCRIPTOR.message_types_by_name['RoleMessage'] = _ROLEMESSAGE
DESCRIPTOR.message_types_by_name['ConfigurationProperties'] = _CONFIGURATIONPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoleMessage = _reflection.GeneratedProtocolMessageType('RoleMessage', (_message.Message,), dict(
  DESCRIPTOR = _ROLEMESSAGE,
  __module__ = 'Devialet.IMASlave4U.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.IMASlave4U.RoleMessage)
  ))
_sym_db.RegisterMessage(RoleMessage)

ConfigurationProperties = _reflection.GeneratedProtocolMessageType('ConfigurationProperties', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONPROPERTIES,
  __module__ = 'Devialet.IMASlave4U.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.IMASlave4U.ConfigurationProperties)
  ))
_sym_db.RegisterMessage(ConfigurationProperties)



_CONFIGURATION = _descriptor.ServiceDescriptor(
  name='Configuration',
  full_name='Devialet.IMASlave4U.Configuration',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>=\010\001\032 io.dvlt.imaslave4u.configuration\"\027ConfigurationProperties'),
  serialized_start=533,
  serialized_end=614,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATION)

DESCRIPTOR.services_by_name['Configuration'] = _CONFIGURATION

# @@protoc_insertion_point(module_scope)
