# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/Collector/LogFacility.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/Collector/LogFacility.proto',
  package='Devialet.Collector',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$Devialet/Collector/LogFacility.proto\x12\x12\x44\x65vialet.Collector\x1a\x1bgoogle/protobuf/empty.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\"<\n\nStorageKey\x12\x14\n\x0cserialNumber\x18\x01 \x01(\t\x12\x18\n\ttimestamp\x18\x02 \x01(\x03\x42\x05\xea>\x02\x08\x01\x32y\n\x0bLogFacility\x12\x44\n\nuploadLogs\x12\x1e.Devialet.Collector.StorageKey\x1a\x16.google.protobuf.Empty\x1a$\xc2>!\x08\x01\x1a\x1dio.dvlt.collector.logfacilityb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,])




_STORAGEKEY = _descriptor.Descriptor(
  name='StorageKey',
  full_name='Devialet.Collector.StorageKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialNumber', full_name='Devialet.Collector.StorageKey.serialNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Devialet.Collector.StorageKey.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352>\002\010\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=194,
)

DESCRIPTOR.message_types_by_name['StorageKey'] = _STORAGEKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorageKey = _reflection.GeneratedProtocolMessageType('StorageKey', (_message.Message,), dict(
  DESCRIPTOR = _STORAGEKEY,
  __module__ = 'Devialet.Collector.LogFacility_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.Collector.StorageKey)
  ))
_sym_db.RegisterMessage(StorageKey)


_STORAGEKEY.fields_by_name['timestamp']._options = None

_LOGFACILITY = _descriptor.ServiceDescriptor(
  name='LogFacility',
  full_name='Devialet.Collector.LogFacility',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>!\010\001\032\035io.dvlt.collector.logfacility'),
  serialized_start=196,
  serialized_end=317,
  methods=[
  _descriptor.MethodDescriptor(
    name='uploadLogs',
    full_name='Devialet.Collector.LogFacility.uploadLogs',
    index=0,
    containing_service=None,
    input_type=_STORAGEKEY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGFACILITY)

DESCRIPTOR.services_by_name['LogFacility'] = _LOGFACILITY

# @@protoc_insertion_point(module_scope)
