# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/CallMeMaybe/DefaultMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/CallMeMaybe/DefaultMessages.proto',
  package='Devialet.CallMeMaybe',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*Devialet/CallMeMaybe/DefaultMessages.proto\x12\x14\x44\x65vialet.CallMeMaybe\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\"N\n\x11\x44\x65\x66\x61ultProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\"\x17\n\x02Id\x12\x11\n\x02id\x18\x01 \x01(\x0c\x42\x05\xca>\x02\x08\x01\x62\x06proto3')
  ,
  dependencies=[Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,])




_DEFAULTPROPERTIES = _descriptor.Descriptor(
  name='DefaultProperties',
  full_name='Devialet.CallMeMaybe.DefaultProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.CallMeMaybe.DefaultProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=231,
)


_ID = _descriptor.Descriptor(
  name='Id',
  full_name='Devialet.CallMeMaybe.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Devialet.CallMeMaybe.Id.id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\312>\002\010\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=256,
)

_DEFAULTPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
DESCRIPTOR.message_types_by_name['DefaultProperties'] = _DEFAULTPROPERTIES
DESCRIPTOR.message_types_by_name['Id'] = _ID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DefaultProperties = _reflection.GeneratedProtocolMessageType('DefaultProperties', (_message.Message,), dict(
  DESCRIPTOR = _DEFAULTPROPERTIES,
  __module__ = 'Devialet.CallMeMaybe.DefaultMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.DefaultProperties)
  ))
_sym_db.RegisterMessage(DefaultProperties)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'Devialet.CallMeMaybe.DefaultMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Id)
  ))
_sym_db.RegisterMessage(Id)


_ID.fields_by_name['id']._options = None
# @@protoc_insertion_point(module_scope)
