# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/GetThePartyStarted/DeviceInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/GetThePartyStarted/DeviceInfo.proto',
  package='Devialet.GetThePartyStarted',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,Devialet/GetThePartyStarted/DeviceInfo.proto\x12\x1b\x44\x65vialet.GetThePartyStarted\"\xf0\x02\n\nDeviceInfo\x12\x14\n\x0cserialNumber\x18\x01 \x01(\t\x12\x11\n\tproductId\x18\x02 \x01(\t\x12\x19\n\x11primaryMacAddress\x18\x03 \x01(\x0c\x12\x11\n\tmodelName\x18\x04 \x01(\t\x12\x17\n\x0fhardwareVersion\x18\x05 \x01(\t\x12\x18\n\x10manufacturerName\x18\x06 \x01(\t\x12\x12\n\nsystemName\x18\x07 \x01(\t\x12\x15\n\rsystemVersion\x18\x08 \x01(\t\x12\x12\n\ndeviceName\x18\t \x01(\t\x12\x17\n\x0f\x65thernetEnabled\x18\n \x01(\x08\x12\x12\n\nplcEnabled\x18\x0b \x01(\x08\x12\x15\n\rwiFi24Enabled\x18\x0c \x01(\x08\x12\x15\n\rwiFi50Enabled\x18\r \x01(\x08\x12\x1f\n\x17\x62luetoothClassicEnabled\x18\x0e \x01(\x08\x12\x1d\n\x15\x62luetoothSmartEnabled\x18\x0f \x01(\x08\x62\x06proto3')
)




_DEVICEINFO = _descriptor.Descriptor(
  name='DeviceInfo',
  full_name='Devialet.GetThePartyStarted.DeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialNumber', full_name='Devialet.GetThePartyStarted.DeviceInfo.serialNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productId', full_name='Devialet.GetThePartyStarted.DeviceInfo.productId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='primaryMacAddress', full_name='Devialet.GetThePartyStarted.DeviceInfo.primaryMacAddress', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modelName', full_name='Devialet.GetThePartyStarted.DeviceInfo.modelName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hardwareVersion', full_name='Devialet.GetThePartyStarted.DeviceInfo.hardwareVersion', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manufacturerName', full_name='Devialet.GetThePartyStarted.DeviceInfo.manufacturerName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='systemName', full_name='Devialet.GetThePartyStarted.DeviceInfo.systemName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='systemVersion', full_name='Devialet.GetThePartyStarted.DeviceInfo.systemVersion', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='Devialet.GetThePartyStarted.DeviceInfo.deviceName', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ethernetEnabled', full_name='Devialet.GetThePartyStarted.DeviceInfo.ethernetEnabled', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plcEnabled', full_name='Devialet.GetThePartyStarted.DeviceInfo.plcEnabled', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wiFi24Enabled', full_name='Devialet.GetThePartyStarted.DeviceInfo.wiFi24Enabled', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wiFi50Enabled', full_name='Devialet.GetThePartyStarted.DeviceInfo.wiFi50Enabled', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bluetoothClassicEnabled', full_name='Devialet.GetThePartyStarted.DeviceInfo.bluetoothClassicEnabled', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bluetoothSmartEnabled', full_name='Devialet.GetThePartyStarted.DeviceInfo.bluetoothSmartEnabled', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=446,
)

DESCRIPTOR.message_types_by_name['DeviceInfo'] = _DEVICEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceInfo = _reflection.GeneratedProtocolMessageType('DeviceInfo', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEINFO,
  __module__ = 'Devialet.GetThePartyStarted.DeviceInfo_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.GetThePartyStarted.DeviceInfo)
  ))
_sym_db.RegisterMessage(DeviceInfo)


# @@protoc_insertion_point(module_scope)
