# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/GetThePartyStarted/NetworkConfiguration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/GetThePartyStarted/NetworkConfiguration.proto',
  package='Devialet.GetThePartyStarted',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n6Devialet/GetThePartyStarted/NetworkConfiguration.proto\x12\x1b\x44\x65vialet.GetThePartyStarted\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\"\x93\x04\n\x14NetworkConfiguration\x12\x44\n\x04wiFi\x18\x01 \x01(\x0b\x32\x36.Devialet.GetThePartyStarted.NetworkConfiguration.WiFi\x12\x42\n\x03plc\x18\x02 \x01(\x0b\x32\x35.Devialet.GetThePartyStarted.NetworkConfiguration.Plc\x1a\xb3\x02\n\x04WiFi\x12P\n\x08networks\x18\x01 \x03(\x0b\x32>.Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.Network\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x1a\xc7\x01\n\x07Network\x12Q\n\x04type\x18\x01 \x01(\x0e\x32\x43.Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.Network.Type\x12\x1c\n\x14serviceSetIdentifier\x18\x02 \x01(\x0c\x12\x1b\n\x0cpreSharedKey\x18\x03 \x01(\x0c\x42\x05\xc2>\x02\x08\x01\".\n\x04Type\x12\x0b\n\x07Station\x10\x00\x12\x08\n\x04Mesh\x10\x01\x12\x0f\n\x0b\x41\x63\x63\x65ssPoint\x10\x02\x1a;\n\x03Plc\x12#\n\x14networkMembershipKey\x18\x01 \x01(\x0c\x42\x05\xc2>\x02\x08\x01\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,])



_NETWORKCONFIGURATION_WIFI_NETWORK_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.Network.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Station', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Mesh', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AccessPoint', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=557,
  serialized_end=603,
)
_sym_db.RegisterEnumDescriptor(_NETWORKCONFIGURATION_WIFI_NETWORK_TYPE)


_NETWORKCONFIGURATION_WIFI_NETWORK = _descriptor.Descriptor(
  name='Network',
  full_name='Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.Network',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.Network.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSetIdentifier', full_name='Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.Network.serviceSetIdentifier', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preSharedKey', full_name='Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.Network.preSharedKey', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\302>\002\010\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NETWORKCONFIGURATION_WIFI_NETWORK_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=603,
)

_NETWORKCONFIGURATION_WIFI = _descriptor.Descriptor(
  name='WiFi',
  full_name='Devialet.GetThePartyStarted.NetworkConfiguration.WiFi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='networks', full_name='Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.networks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NETWORKCONFIGURATION_WIFI_NETWORK, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=603,
)

_NETWORKCONFIGURATION_PLC = _descriptor.Descriptor(
  name='Plc',
  full_name='Devialet.GetThePartyStarted.NetworkConfiguration.Plc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='networkMembershipKey', full_name='Devialet.GetThePartyStarted.NetworkConfiguration.Plc.networkMembershipKey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\302>\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='Devialet.GetThePartyStarted.NetworkConfiguration.Plc.enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=664,
)

_NETWORKCONFIGURATION = _descriptor.Descriptor(
  name='NetworkConfiguration',
  full_name='Devialet.GetThePartyStarted.NetworkConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wiFi', full_name='Devialet.GetThePartyStarted.NetworkConfiguration.wiFi', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plc', full_name='Devialet.GetThePartyStarted.NetworkConfiguration.plc', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NETWORKCONFIGURATION_WIFI, _NETWORKCONFIGURATION_PLC, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=664,
)

_NETWORKCONFIGURATION_WIFI_NETWORK.fields_by_name['type'].enum_type = _NETWORKCONFIGURATION_WIFI_NETWORK_TYPE
_NETWORKCONFIGURATION_WIFI_NETWORK.containing_type = _NETWORKCONFIGURATION_WIFI
_NETWORKCONFIGURATION_WIFI_NETWORK_TYPE.containing_type = _NETWORKCONFIGURATION_WIFI_NETWORK
_NETWORKCONFIGURATION_WIFI.fields_by_name['networks'].message_type = _NETWORKCONFIGURATION_WIFI_NETWORK
_NETWORKCONFIGURATION_WIFI.containing_type = _NETWORKCONFIGURATION
_NETWORKCONFIGURATION_PLC.containing_type = _NETWORKCONFIGURATION
_NETWORKCONFIGURATION.fields_by_name['wiFi'].message_type = _NETWORKCONFIGURATION_WIFI
_NETWORKCONFIGURATION.fields_by_name['plc'].message_type = _NETWORKCONFIGURATION_PLC
DESCRIPTOR.message_types_by_name['NetworkConfiguration'] = _NETWORKCONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkConfiguration = _reflection.GeneratedProtocolMessageType('NetworkConfiguration', (_message.Message,), dict(

  WiFi = _reflection.GeneratedProtocolMessageType('WiFi', (_message.Message,), dict(

    Network = _reflection.GeneratedProtocolMessageType('Network', (_message.Message,), dict(
      DESCRIPTOR = _NETWORKCONFIGURATION_WIFI_NETWORK,
      __module__ = 'Devialet.GetThePartyStarted.NetworkConfiguration_pb2'
      # @@protoc_insertion_point(class_scope:Devialet.GetThePartyStarted.NetworkConfiguration.WiFi.Network)
      ))
    ,
    DESCRIPTOR = _NETWORKCONFIGURATION_WIFI,
    __module__ = 'Devialet.GetThePartyStarted.NetworkConfiguration_pb2'
    # @@protoc_insertion_point(class_scope:Devialet.GetThePartyStarted.NetworkConfiguration.WiFi)
    ))
  ,

  Plc = _reflection.GeneratedProtocolMessageType('Plc', (_message.Message,), dict(
    DESCRIPTOR = _NETWORKCONFIGURATION_PLC,
    __module__ = 'Devialet.GetThePartyStarted.NetworkConfiguration_pb2'
    # @@protoc_insertion_point(class_scope:Devialet.GetThePartyStarted.NetworkConfiguration.Plc)
    ))
  ,
  DESCRIPTOR = _NETWORKCONFIGURATION,
  __module__ = 'Devialet.GetThePartyStarted.NetworkConfiguration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.GetThePartyStarted.NetworkConfiguration)
  ))
_sym_db.RegisterMessage(NetworkConfiguration)
_sym_db.RegisterMessage(NetworkConfiguration.WiFi)
_sym_db.RegisterMessage(NetworkConfiguration.WiFi.Network)
_sym_db.RegisterMessage(NetworkConfiguration.Plc)


_NETWORKCONFIGURATION_WIFI_NETWORK.fields_by_name['preSharedKey']._options = None
_NETWORKCONFIGURATION_PLC.fields_by_name['networkMembershipKey']._options = None
# @@protoc_insertion_point(module_scope)
