# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/SourceOfAll/BaseService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/SourceOfAll/BaseService.proto',
  package='Devialet.SourceOfAll',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&Devialet/SourceOfAll/BaseService.proto\x12\x14\x44\x65vialet.SourceOfAll\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto2)\n\x0b\x42\x61seService\x1a\x1a\xc2>\x17\x08\x01\x1a\x13io.dvlt.sourceofallb\x06proto3')
  ,
  dependencies=[Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BASESERVICE = _descriptor.ServiceDescriptor(
  name='BaseService',
  full_name='Devialet.SourceOfAll.BaseService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>\027\010\001\032\023io.dvlt.sourceofall'),
  serialized_start=149,
  serialized_end=190,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_BASESERVICE)

DESCRIPTOR.services_by_name['BaseService'] = _BASESERVICE

# @@protoc_insertion_point(module_scope)
