# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/SourceOfAll/Configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import DefaultMessages_pb2 as Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2
from Devialet.SourceOfAll import BaseService_pb2 as Devialet_dot_SourceOfAll_dot_BaseService__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/SourceOfAll/Configuration.proto',
  package='Devialet.SourceOfAll',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(Devialet/SourceOfAll/Configuration.proto\x12\x14\x44\x65vialet.SourceOfAll\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a*Devialet/CallMeMaybe/DefaultMessages.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\x1a&Devialet/SourceOfAll/BaseService.proto\"\xa3\x01\n\x1a\x43onfigurationTargetMessage\x12I\n\x04type\x18\x01 \x01(\x0e\x32;.Devialet.SourceOfAll.ConfigurationTargetMessage.TargetType\":\n\nTargetType\x12\x15\n\x11UnknownTargetType\x10\x00\x12\t\n\x05Group\x10\x01\x12\n\n\x06System\x10\x02\"\x83\x01\n\x15PlaybackTargetMessage\x12@\n\x06target\x18\x01 \x01(\x0b\x32\x30.Devialet.SourceOfAll.ConfigurationTargetMessage\x12(\n\x06system\x18\x02 \x01(\x0b\x32\x18.Devialet.CallMeMaybe.Id\"\xd5\x03\n\x17\x43onfigurationProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12\x12\n\nprettyName\x18\x02 \x01(\t\x12\"\n\x13\x63\x61nChangePrettyName\x18\x03 \x01(\x08\x42\x05\xda>\x02 \x01\x12\x43\n\x0eplaybackTarget\x18\x04 \x01(\x0b\x32+.Devialet.SourceOfAll.PlaybackTargetMessage\x12\x46\n\x0cremoteTarget\x18\x05 \x01(\x0b\x32\x30.Devialet.SourceOfAll.ConfigurationTargetMessage\x12\x15\n\rdefaultVolume\x18\x06 \x01(\r\x12\x1f\n\x10\x63\x61nChangeLatency\x18\x07 \x01(\x08\x42\x05\xda>\x02 \x01\x12\x16\n\x07latency\x18\x08 \x01(\x03\x42\x05\xea>\x02\x08\x03\x12\"\n\x0e\x64\x65\x66\x61ultLatency\x18\t \x01(\x03\x42\n\xda>\x02\x18\x01\xea>\x02\x08\x03\x12\"\n\x0eminimumLatency\x18\n \x01(\x03\x42\n\xda>\x02\x18\x01\xea>\x02\x08\x03\x12\"\n\x0emaximumLatency\x18\x0b \x01(\x03\x42\n\xda>\x02\x18\x01\xea>\x02\x08\x03\x32\x61\n\rConfiguration\x1aP\xc2>M\x08\x01\x12 Devialet.SourceOfAll.BaseService\x1a\x0e.configuration\"\x17\x43onfigurationPropertiesb\x06proto3')
  ,
  dependencies=[Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,Devialet_dot_SourceOfAll_dot_BaseService__pb2.DESCRIPTOR,])



_CONFIGURATIONTARGETMESSAGE_TARGETTYPE = _descriptor.EnumDescriptor(
  name='TargetType',
  full_name='Devialet.SourceOfAll.ConfigurationTargetMessage.TargetType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnknownTargetType', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Group', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='System', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=341,
  serialized_end=399,
)
_sym_db.RegisterEnumDescriptor(_CONFIGURATIONTARGETMESSAGE_TARGETTYPE)


_CONFIGURATIONTARGETMESSAGE = _descriptor.Descriptor(
  name='ConfigurationTargetMessage',
  full_name='Devialet.SourceOfAll.ConfigurationTargetMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.SourceOfAll.ConfigurationTargetMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIGURATIONTARGETMESSAGE_TARGETTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=399,
)


_PLAYBACKTARGETMESSAGE = _descriptor.Descriptor(
  name='PlaybackTargetMessage',
  full_name='Devialet.SourceOfAll.PlaybackTargetMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='Devialet.SourceOfAll.PlaybackTargetMessage.target', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='system', full_name='Devialet.SourceOfAll.PlaybackTargetMessage.system', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=533,
)


_CONFIGURATIONPROPERTIES = _descriptor.Descriptor(
  name='ConfigurationProperties',
  full_name='Devialet.SourceOfAll.ConfigurationProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.SourceOfAll.ConfigurationProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prettyName', full_name='Devialet.SourceOfAll.ConfigurationProperties.prettyName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='canChangePrettyName', full_name='Devialet.SourceOfAll.ConfigurationProperties.canChangePrettyName', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002 \001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playbackTarget', full_name='Devialet.SourceOfAll.ConfigurationProperties.playbackTarget', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remoteTarget', full_name='Devialet.SourceOfAll.ConfigurationProperties.remoteTarget', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defaultVolume', full_name='Devialet.SourceOfAll.ConfigurationProperties.defaultVolume', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='canChangeLatency', full_name='Devialet.SourceOfAll.ConfigurationProperties.canChangeLatency', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002 \001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latency', full_name='Devialet.SourceOfAll.ConfigurationProperties.latency', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352>\002\010\003'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defaultLatency', full_name='Devialet.SourceOfAll.ConfigurationProperties.defaultLatency', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001\352>\002\010\003'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minimumLatency', full_name='Devialet.SourceOfAll.ConfigurationProperties.minimumLatency', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001\352>\002\010\003'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maximumLatency', full_name='Devialet.SourceOfAll.ConfigurationProperties.maximumLatency', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001\352>\002\010\003'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=1005,
)

_CONFIGURATIONTARGETMESSAGE.fields_by_name['type'].enum_type = _CONFIGURATIONTARGETMESSAGE_TARGETTYPE
_CONFIGURATIONTARGETMESSAGE_TARGETTYPE.containing_type = _CONFIGURATIONTARGETMESSAGE
_PLAYBACKTARGETMESSAGE.fields_by_name['target'].message_type = _CONFIGURATIONTARGETMESSAGE
_PLAYBACKTARGETMESSAGE.fields_by_name['system'].message_type = Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2._ID
_CONFIGURATIONPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_CONFIGURATIONPROPERTIES.fields_by_name['playbackTarget'].message_type = _PLAYBACKTARGETMESSAGE
_CONFIGURATIONPROPERTIES.fields_by_name['remoteTarget'].message_type = _CONFIGURATIONTARGETMESSAGE
DESCRIPTOR.message_types_by_name['ConfigurationTargetMessage'] = _CONFIGURATIONTARGETMESSAGE
DESCRIPTOR.message_types_by_name['PlaybackTargetMessage'] = _PLAYBACKTARGETMESSAGE
DESCRIPTOR.message_types_by_name['ConfigurationProperties'] = _CONFIGURATIONPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigurationTargetMessage = _reflection.GeneratedProtocolMessageType('ConfigurationTargetMessage', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONTARGETMESSAGE,
  __module__ = 'Devialet.SourceOfAll.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SourceOfAll.ConfigurationTargetMessage)
  ))
_sym_db.RegisterMessage(ConfigurationTargetMessage)

PlaybackTargetMessage = _reflection.GeneratedProtocolMessageType('PlaybackTargetMessage', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBACKTARGETMESSAGE,
  __module__ = 'Devialet.SourceOfAll.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SourceOfAll.PlaybackTargetMessage)
  ))
_sym_db.RegisterMessage(PlaybackTargetMessage)

ConfigurationProperties = _reflection.GeneratedProtocolMessageType('ConfigurationProperties', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONPROPERTIES,
  __module__ = 'Devialet.SourceOfAll.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SourceOfAll.ConfigurationProperties)
  ))
_sym_db.RegisterMessage(ConfigurationProperties)


_CONFIGURATIONPROPERTIES.fields_by_name['canChangePrettyName']._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['canChangeLatency']._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['latency']._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['defaultLatency']._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['minimumLatency']._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['maximumLatency']._options = None

_CONFIGURATION = _descriptor.ServiceDescriptor(
  name='Configuration',
  full_name='Devialet.SourceOfAll.Configuration',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>M\010\001\022 Devialet.SourceOfAll.BaseService\032\016.configuration\"\027ConfigurationProperties'),
  serialized_start=1007,
  serialized_end=1104,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATION)

DESCRIPTOR.services_by_name['Configuration'] = _CONFIGURATION

# @@protoc_insertion_point(module_scope)
