# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/SourceOfAll/Metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2
from Devialet.SourceOfAll import BaseService_pb2 as Devialet_dot_SourceOfAll_dot_BaseService__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/SourceOfAll/Metadata.proto',
  package='Devialet.SourceOfAll',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#Devialet/SourceOfAll/Metadata.proto\x12\x14\x44\x65vialet.SourceOfAll\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\x1a&Devialet/SourceOfAll/BaseService.proto\"\xa4\x01\n\x0ePictureMessage\x12\x37\n\x04type\x18\x01 \x01(\x0e\x32).Devialet.SourceOfAll.PictureMessage.Type\x12\x13\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42\x05\xca>\x02\x10\x03\x12\x12\n\x03url\x18\x03 \x01(\tB\x05\xe2>\x02\x08\x01\"0\n\x04Type\x12\x0b\n\x07Unknown\x10\x00\x12\x08\n\x04None\x10\x01\x12\x08\n\x04\x44\x61ta\x10\x02\x12\x07\n\x03Url\x10\x03\"\xdc\x04\n\x12MetadataProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12\x14\n\x05\x61lbum\x18\x02 \x01(\tB\x05\xda>\x02\x18\x01\x12\x1a\n\x0b\x61lbumArtist\x18\x03 \x01(\tB\x05\xda>\x02\x18\x01\x12\x15\n\x06\x61rtist\x18\x04 \x01(\tB\x05\xda>\x02\x18\x01\x12\x17\n\x08\x63omposer\x18\x05 \x01(\tB\x05\xda>\x02\x18\x01\x12\x14\n\x05genre\x18\x06 \x01(\tB\x05\xda>\x02\x18\x01\x12\x17\n\x08location\x18\x07 \x01(\tB\x05\xda>\x02\x18\x01\x12\x1b\n\x0corganization\x18\x08 \x01(\tB\x05\xda>\x02\x18\x01\x12\x14\n\x05title\x18\t \x01(\tB\x05\xda>\x02\x18\x01\x12\x1c\n\x08homepage\x18\n \x01(\tB\n\xda>\x02\x18\x01\xe2>\x02\x08\x01\x12\x1d\n\tdvltTrack\x18\x0b \x01(\x0c\x42\n\xca>\x02\x08\x02\xda>\x02\x18\x01\x12<\n\x07picture\x18\x0c \x01(\x0b\x32$.Devialet.SourceOfAll.PictureMessageB\x05\xda>\x02\x18\x01\x12\x1c\n\x08\x64uration\x18\r \x01(\x03\x42\n\xda>\x02\x18\x01\xea>\x02\x08\x05\x12\x17\n\x08isStream\x18\x0e \x01(\x08\x42\x05\xda>\x02\x18\x01\x12L\n\tmediaType\x18\x0f \x01(\x0e\x32\x32.Devialet.SourceOfAll.MetadataProperties.MediaTypeB\x05\xda>\x02\x18\x01\"G\n\tMediaType\x12\x0b\n\x07Unknown\x10\x00\x12\t\n\x05Track\x10\x01\x12\x0b\n\x07Podcast\x10\x02\x12\x0b\n\x07Station\x10\x03\x12\x08\n\x04Live\x10\x04\x32R\n\x08Metadata\x1a\x46\xc2>C\x08\x01\x12 Devialet.SourceOfAll.BaseService\x1a\t.metadata\"\x12MetadataPropertiesb\x06proto3')
  ,
  dependencies=[Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,Devialet_dot_SourceOfAll_dot_BaseService__pb2.DESCRIPTOR,])



_PICTUREMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Devialet.SourceOfAll.PictureMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='None', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Data', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Url', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=303,
  serialized_end=351,
)
_sym_db.RegisterEnumDescriptor(_PICTUREMESSAGE_TYPE)

_METADATAPROPERTIES_MEDIATYPE = _descriptor.EnumDescriptor(
  name='MediaType',
  full_name='Devialet.SourceOfAll.MetadataProperties.MediaType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Track', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Podcast', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Station', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Live', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=887,
  serialized_end=958,
)
_sym_db.RegisterEnumDescriptor(_METADATAPROPERTIES_MEDIATYPE)


_PICTUREMESSAGE = _descriptor.Descriptor(
  name='PictureMessage',
  full_name='Devialet.SourceOfAll.PictureMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.SourceOfAll.PictureMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Devialet.SourceOfAll.PictureMessage.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\312>\002\020\003'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='Devialet.SourceOfAll.PictureMessage.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\342>\002\010\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PICTUREMESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=351,
)


_METADATAPROPERTIES = _descriptor.Descriptor(
  name='MetadataProperties',
  full_name='Devialet.SourceOfAll.MetadataProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.SourceOfAll.MetadataProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='album', full_name='Devialet.SourceOfAll.MetadataProperties.album', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='albumArtist', full_name='Devialet.SourceOfAll.MetadataProperties.albumArtist', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='artist', full_name='Devialet.SourceOfAll.MetadataProperties.artist', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='composer', full_name='Devialet.SourceOfAll.MetadataProperties.composer', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='Devialet.SourceOfAll.MetadataProperties.genre', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='Devialet.SourceOfAll.MetadataProperties.location', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organization', full_name='Devialet.SourceOfAll.MetadataProperties.organization', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='Devialet.SourceOfAll.MetadataProperties.title', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='homepage', full_name='Devialet.SourceOfAll.MetadataProperties.homepage', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001\342>\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dvltTrack', full_name='Devialet.SourceOfAll.MetadataProperties.dvltTrack', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\312>\002\010\002\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='picture', full_name='Devialet.SourceOfAll.MetadataProperties.picture', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='Devialet.SourceOfAll.MetadataProperties.duration', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001\352>\002\010\005'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isStream', full_name='Devialet.SourceOfAll.MetadataProperties.isStream', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mediaType', full_name='Devialet.SourceOfAll.MetadataProperties.mediaType', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _METADATAPROPERTIES_MEDIATYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=958,
)

_PICTUREMESSAGE.fields_by_name['type'].enum_type = _PICTUREMESSAGE_TYPE
_PICTUREMESSAGE_TYPE.containing_type = _PICTUREMESSAGE
_METADATAPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_METADATAPROPERTIES.fields_by_name['picture'].message_type = _PICTUREMESSAGE
_METADATAPROPERTIES.fields_by_name['mediaType'].enum_type = _METADATAPROPERTIES_MEDIATYPE
_METADATAPROPERTIES_MEDIATYPE.containing_type = _METADATAPROPERTIES
DESCRIPTOR.message_types_by_name['PictureMessage'] = _PICTUREMESSAGE
DESCRIPTOR.message_types_by_name['MetadataProperties'] = _METADATAPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PictureMessage = _reflection.GeneratedProtocolMessageType('PictureMessage', (_message.Message,), dict(
  DESCRIPTOR = _PICTUREMESSAGE,
  __module__ = 'Devialet.SourceOfAll.Metadata_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SourceOfAll.PictureMessage)
  ))
_sym_db.RegisterMessage(PictureMessage)

MetadataProperties = _reflection.GeneratedProtocolMessageType('MetadataProperties', (_message.Message,), dict(
  DESCRIPTOR = _METADATAPROPERTIES,
  __module__ = 'Devialet.SourceOfAll.Metadata_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SourceOfAll.MetadataProperties)
  ))
_sym_db.RegisterMessage(MetadataProperties)


_PICTUREMESSAGE.fields_by_name['data']._options = None
_PICTUREMESSAGE.fields_by_name['url']._options = None
_METADATAPROPERTIES.fields_by_name['album']._options = None
_METADATAPROPERTIES.fields_by_name['albumArtist']._options = None
_METADATAPROPERTIES.fields_by_name['artist']._options = None
_METADATAPROPERTIES.fields_by_name['composer']._options = None
_METADATAPROPERTIES.fields_by_name['genre']._options = None
_METADATAPROPERTIES.fields_by_name['location']._options = None
_METADATAPROPERTIES.fields_by_name['organization']._options = None
_METADATAPROPERTIES.fields_by_name['title']._options = None
_METADATAPROPERTIES.fields_by_name['homepage']._options = None
_METADATAPROPERTIES.fields_by_name['dvltTrack']._options = None
_METADATAPROPERTIES.fields_by_name['picture']._options = None
_METADATAPROPERTIES.fields_by_name['duration']._options = None
_METADATAPROPERTIES.fields_by_name['isStream']._options = None
_METADATAPROPERTIES.fields_by_name['mediaType']._options = None

_METADATA = _descriptor.ServiceDescriptor(
  name='Metadata',
  full_name='Devialet.SourceOfAll.Metadata',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>C\010\001\022 Devialet.SourceOfAll.BaseService\032\t.metadata\"\022MetadataProperties'),
  serialized_start=960,
  serialized_end=1042,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_METADATA)

DESCRIPTOR.services_by_name['Metadata'] = _METADATA

# @@protoc_insertion_point(module_scope)
