# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/SourceOfAll/Source.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import DefaultMessages_pb2 as Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2
from Devialet.SourceOfAll import BaseService_pb2 as Devialet_dot_SourceOfAll_dot_BaseService__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/SourceOfAll/Source.proto',
  package='Devialet.SourceOfAll',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!Devialet/SourceOfAll/Source.proto\x12\x14\x44\x65vialet.SourceOfAll\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a*Devialet/CallMeMaybe/DefaultMessages.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\x1a&Devialet/SourceOfAll/BaseService.proto\"N\n\x0cIconsMessage\x12\x12\n\x03low\x18\x01 \x01(\tB\x05\xe2>\x02\x08\x01\x12\x15\n\x06medium\x18\x02 \x01(\tB\x05\xe2>\x02\x08\x01\x12\x13\n\x04high\x18\x03 \x01(\tB\x05\xe2>\x02\x08\x01\"\x97\x01\n\x10SourceProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12\x0e\n\x06select\x18\x02 \x01(\x08\x12\x38\n\x05icons\x18\x03 \x01(\x0b\x32\".Devialet.SourceOfAll.IconsMessageB\x05\xda>\x02\x18\x01\x32L\n\x06Source\x1a\x42\xc2>?\x08\x01\x12 Devialet.SourceOfAll.BaseService\x1a\x07.source\"\x10SourcePropertiesb\x06proto3')
  ,
  dependencies=[Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,Devialet_dot_SourceOfAll_dot_BaseService__pb2.DESCRIPTOR,])




_ICONSMESSAGE = _descriptor.Descriptor(
  name='IconsMessage',
  full_name='Devialet.SourceOfAll.IconsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='low', full_name='Devialet.SourceOfAll.IconsMessage.low', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\342>\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='medium', full_name='Devialet.SourceOfAll.IconsMessage.medium', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\342>\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='Devialet.SourceOfAll.IconsMessage.high', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\342>\002\010\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=306,
)


_SOURCEPROPERTIES = _descriptor.Descriptor(
  name='SourceProperties',
  full_name='Devialet.SourceOfAll.SourceProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.SourceOfAll.SourceProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='select', full_name='Devialet.SourceOfAll.SourceProperties.select', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icons', full_name='Devialet.SourceOfAll.SourceProperties.icons', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=460,
)

_SOURCEPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_SOURCEPROPERTIES.fields_by_name['icons'].message_type = _ICONSMESSAGE
DESCRIPTOR.message_types_by_name['IconsMessage'] = _ICONSMESSAGE
DESCRIPTOR.message_types_by_name['SourceProperties'] = _SOURCEPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IconsMessage = _reflection.GeneratedProtocolMessageType('IconsMessage', (_message.Message,), dict(
  DESCRIPTOR = _ICONSMESSAGE,
  __module__ = 'Devialet.SourceOfAll.Source_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SourceOfAll.IconsMessage)
  ))
_sym_db.RegisterMessage(IconsMessage)

SourceProperties = _reflection.GeneratedProtocolMessageType('SourceProperties', (_message.Message,), dict(
  DESCRIPTOR = _SOURCEPROPERTIES,
  __module__ = 'Devialet.SourceOfAll.Source_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SourceOfAll.SourceProperties)
  ))
_sym_db.RegisterMessage(SourceProperties)


_ICONSMESSAGE.fields_by_name['low']._options = None
_ICONSMESSAGE.fields_by_name['medium']._options = None
_ICONSMESSAGE.fields_by_name['high']._options = None
_SOURCEPROPERTIES.fields_by_name['icons']._options = None

_SOURCE = _descriptor.ServiceDescriptor(
  name='Source',
  full_name='Devialet.SourceOfAll.Source',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>?\010\001\022 Devialet.SourceOfAll.BaseService\032\007.source\"\020SourceProperties'),
  serialized_start=462,
  serialized_end=538,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_SOURCE)

DESCRIPTOR.services_by_name['Source'] = _SOURCE

# @@protoc_insertion_point(module_scope)
