# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/SourceOfAll/Topology.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import DefaultMessages_pb2 as Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2
from Devialet.SourceOfAll import BaseService_pb2 as Devialet_dot_SourceOfAll_dot_BaseService__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/SourceOfAll/Topology.proto',
  package='Devialet.SourceOfAll',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#Devialet/SourceOfAll/Topology.proto\x12\x14\x44\x65vialet.SourceOfAll\x1a\x1bgoogle/protobuf/empty.proto\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a*Devialet/CallMeMaybe/DefaultMessages.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\x1a&Devialet/SourceOfAll/BaseService.proto\"\x9c\x01\n\x12TopologyProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12\x17\n\x08isActive\x18\x02 \x01(\x08\x42\x05\xda>\x02\x18\x01\x12\x32\n\trenderers\x18\x03 \x03(\x0b\x32\x18.Devialet.CallMeMaybe.IdB\x05\xda>\x02\x18\x01\x32R\n\x08Topology\x1a\x46\xc2>C\x08\x01\x12 Devialet.SourceOfAll.BaseService\x1a\t.topology\"\x12TopologyPropertiesb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,Devialet_dot_SourceOfAll_dot_BaseService__pb2.DESCRIPTOR,])




_TOPOLOGYPROPERTIES = _descriptor.Descriptor(
  name='TopologyProperties',
  full_name='Devialet.SourceOfAll.TopologyProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.SourceOfAll.TopologyProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isActive', full_name='Devialet.SourceOfAll.TopologyProperties.isActive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='renderers', full_name='Devialet.SourceOfAll.TopologyProperties.renderers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=416,
)

_TOPOLOGYPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_TOPOLOGYPROPERTIES.fields_by_name['renderers'].message_type = Devialet_dot_CallMeMaybe_dot_DefaultMessages__pb2._ID
DESCRIPTOR.message_types_by_name['TopologyProperties'] = _TOPOLOGYPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopologyProperties = _reflection.GeneratedProtocolMessageType('TopologyProperties', (_message.Message,), dict(
  DESCRIPTOR = _TOPOLOGYPROPERTIES,
  __module__ = 'Devialet.SourceOfAll.Topology_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SourceOfAll.TopologyProperties)
  ))
_sym_db.RegisterMessage(TopologyProperties)


_TOPOLOGYPROPERTIES.fields_by_name['isActive']._options = None
_TOPOLOGYPROPERTIES.fields_by_name['renderers']._options = None

_TOPOLOGY = _descriptor.ServiceDescriptor(
  name='Topology',
  full_name='Devialet.SourceOfAll.Topology',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>C\010\001\022 Devialet.SourceOfAll.BaseService\032\t.topology\"\022TopologyProperties'),
  serialized_start=418,
  serialized_end=500,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_TOPOLOGY)

DESCRIPTOR.services_by_name['Topology'] = _TOPOLOGY

# @@protoc_insertion_point(module_scope)
