# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/Blue/Configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2
from Devialet.SourceOfAll import Configuration_pb2 as Devialet_dot_SourceOfAll_dot_Configuration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/Blue/Configuration.proto',
  package='Devialet.Blue',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!Devialet/Blue/Configuration.proto\x12\rDevialet.Blue\x1a\x1bgoogle/protobuf/empty.proto\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\x1a(Devialet/SourceOfAll/Configuration.proto\"Q\n\nPeerDevice\x12\x12\n\nmacAddress\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06paired\x18\x03 \x01(\x08\x12\x11\n\tconnected\x18\x04 \x01(\x08\"\x8d\x03\n\x17\x43onfigurationProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12\x1d\n\x0eisDiscoverable\x18\x02 \x01(\x08\x42\x05\xda>\x02\x18\x01\x12+\n\x17\x64iscoverabilityDuration\x18\x03 \x01(\x03\x42\n\xda>\x02 \x01\xea>\x02\x08\x02\x12\x1e\n\x0fhasRemoteDevice\x18\x04 \x01(\x08\x42\x05\xda>\x02\x18\x01\x12 \n\x11\x63urrentPeerDevice\x18\x05 \x01(\x04\x42\x05\xda>\x02\x18\x01\x12Z\n\x0bpeerDevices\x18\x06 \x03(\x0b\x32\x37.Devialet.Blue.ConfigurationProperties.PeerDevicesEntryB\x0c\xd2>\x02\x08\x01\xda>\x04\x18\x01\x38\x01\x1aM\n\x10PeerDevicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.Devialet.Blue.PeerDevice:\x02\x38\x01\x32\xb2\x02\n\rConfiguration\x12\x46\n\x14startDiscoverability\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x45\n\x13stopDiscoverability\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12G\n\x15toggleDiscoverability\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x1aI\xc2>F\x08\x01\x12\"Devialet.SourceOfAll.Configuration\x1a\x05.blue\"\x17\x43onfigurationPropertiesb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,Devialet_dot_SourceOfAll_dot_Configuration__pb2.DESCRIPTOR,])




_PEERDEVICE = _descriptor.Descriptor(
  name='PeerDevice',
  full_name='Devialet.Blue.PeerDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='macAddress', full_name='Devialet.Blue.PeerDevice.macAddress', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Devialet.Blue.PeerDevice.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paired', full_name='Devialet.Blue.PeerDevice.paired', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connected', full_name='Devialet.Blue.PeerDevice.connected', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=289,
)


_CONFIGURATIONPROPERTIES_PEERDEVICESENTRY = _descriptor.Descriptor(
  name='PeerDevicesEntry',
  full_name='Devialet.Blue.ConfigurationProperties.PeerDevicesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Devialet.Blue.ConfigurationProperties.PeerDevicesEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.Blue.ConfigurationProperties.PeerDevicesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=689,
)

_CONFIGURATIONPROPERTIES = _descriptor.Descriptor(
  name='ConfigurationProperties',
  full_name='Devialet.Blue.ConfigurationProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.Blue.ConfigurationProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isDiscoverable', full_name='Devialet.Blue.ConfigurationProperties.isDiscoverable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discoverabilityDuration', full_name='Devialet.Blue.ConfigurationProperties.discoverabilityDuration', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002 \001\352>\002\010\002'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hasRemoteDevice', full_name='Devialet.Blue.ConfigurationProperties.hasRemoteDevice', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentPeerDevice', full_name='Devialet.Blue.ConfigurationProperties.currentPeerDevice', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\332>\002\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peerDevices', full_name='Devialet.Blue.ConfigurationProperties.peerDevices', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\322>\002\010\001\332>\004\030\0018\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONFIGURATIONPROPERTIES_PEERDEVICESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=689,
)

_CONFIGURATIONPROPERTIES_PEERDEVICESENTRY.fields_by_name['value'].message_type = _PEERDEVICE
_CONFIGURATIONPROPERTIES_PEERDEVICESENTRY.containing_type = _CONFIGURATIONPROPERTIES
_CONFIGURATIONPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_CONFIGURATIONPROPERTIES.fields_by_name['peerDevices'].message_type = _CONFIGURATIONPROPERTIES_PEERDEVICESENTRY
DESCRIPTOR.message_types_by_name['PeerDevice'] = _PEERDEVICE
DESCRIPTOR.message_types_by_name['ConfigurationProperties'] = _CONFIGURATIONPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PeerDevice = _reflection.GeneratedProtocolMessageType('PeerDevice', (_message.Message,), dict(
  DESCRIPTOR = _PEERDEVICE,
  __module__ = 'Devialet.Blue.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.Blue.PeerDevice)
  ))
_sym_db.RegisterMessage(PeerDevice)

ConfigurationProperties = _reflection.GeneratedProtocolMessageType('ConfigurationProperties', (_message.Message,), dict(

  PeerDevicesEntry = _reflection.GeneratedProtocolMessageType('PeerDevicesEntry', (_message.Message,), dict(
    DESCRIPTOR = _CONFIGURATIONPROPERTIES_PEERDEVICESENTRY,
    __module__ = 'Devialet.Blue.Configuration_pb2'
    # @@protoc_insertion_point(class_scope:Devialet.Blue.ConfigurationProperties.PeerDevicesEntry)
    ))
  ,
  DESCRIPTOR = _CONFIGURATIONPROPERTIES,
  __module__ = 'Devialet.Blue.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.Blue.ConfigurationProperties)
  ))
_sym_db.RegisterMessage(ConfigurationProperties)
_sym_db.RegisterMessage(ConfigurationProperties.PeerDevicesEntry)


_CONFIGURATIONPROPERTIES_PEERDEVICESENTRY._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['isDiscoverable']._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['discoverabilityDuration']._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['hasRemoteDevice']._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['currentPeerDevice']._options = None
_CONFIGURATIONPROPERTIES.fields_by_name['peerDevices']._options = None

_CONFIGURATION = _descriptor.ServiceDescriptor(
  name='Configuration',
  full_name='Devialet.Blue.Configuration',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>F\010\001\022\"Devialet.SourceOfAll.Configuration\032\005.blue\"\027ConfigurationProperties'),
  serialized_start=692,
  serialized_end=998,
  methods=[
  _descriptor.MethodDescriptor(
    name='startDiscoverability',
    full_name='Devialet.Blue.Configuration.startDiscoverability',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopDiscoverability',
    full_name='Devialet.Blue.Configuration.stopDiscoverability',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='toggleDiscoverability',
    full_name='Devialet.Blue.Configuration.toggleDiscoverability',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATION)

DESCRIPTOR.services_by_name['Configuration'] = _CONFIGURATION

# @@protoc_insertion_point(module_scope)
