# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Devialet/UnderTheBridge/Configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Devialet.CallMeMaybe import CallMeMaybe_pb2 as Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2
from Devialet.CallMeMaybe import GeneratorOptions_pb2 as Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Devialet/UnderTheBridge/Configuration.proto',
  package='Devialet.UnderTheBridge',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+Devialet/UnderTheBridge/Configuration.proto\x12\x17\x44\x65vialet.UnderTheBridge\x1a&Devialet/CallMeMaybe/CallMeMaybe.proto\x1a+Devialet/CallMeMaybe/GeneratorOptions.proto\"\x84\x02\n\x17\x43onfigurationProperties\x12\x39\n\x06parent\x18\x01 \x01(\x0b\x32).Devialet.CallMeMaybe.InterfaceProperties\x12_\n\x12\x61udioRoutingPolicy\x18\x02 \x01(\x0e\x32\x43.Devialet.UnderTheBridge.ConfigurationProperties.AudioRoutingPolicy\"M\n\x12\x41udioRoutingPolicy\x12\x0b\n\x07Unknown\x10\x00\x12\x08\n\x04\x41uto\x10\x01\x12\x0f\n\x0bWifiOverPlc\x10\x02\x12\x0f\n\x0bPlcOverWifi\x10\x03\x32U\n\rConfiguration\x1a\x44\xc2>A\x08\x01\x1a$io.dvlt.underthebridge.configuration\"\x17\x43onfigurationPropertiesb\x06proto3')
  ,
  dependencies=[Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,Devialet_dot_CallMeMaybe_dot_GeneratorOptions__pb2.DESCRIPTOR,])



_CONFIGURATIONPROPERTIES_AUDIOROUTINGPOLICY = _descriptor.EnumDescriptor(
  name='AudioRoutingPolicy',
  full_name='Devialet.UnderTheBridge.ConfigurationProperties.AudioRoutingPolicy',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Auto', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WifiOverPlc', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PlcOverWifi', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=341,
  serialized_end=418,
)
_sym_db.RegisterEnumDescriptor(_CONFIGURATIONPROPERTIES_AUDIOROUTINGPOLICY)


_CONFIGURATIONPROPERTIES = _descriptor.Descriptor(
  name='ConfigurationProperties',
  full_name='Devialet.UnderTheBridge.ConfigurationProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='Devialet.UnderTheBridge.ConfigurationProperties.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audioRoutingPolicy', full_name='Devialet.UnderTheBridge.ConfigurationProperties.audioRoutingPolicy', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIGURATIONPROPERTIES_AUDIOROUTINGPOLICY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=418,
)

_CONFIGURATIONPROPERTIES.fields_by_name['parent'].message_type = Devialet_dot_CallMeMaybe_dot_CallMeMaybe__pb2._INTERFACEPROPERTIES
_CONFIGURATIONPROPERTIES.fields_by_name['audioRoutingPolicy'].enum_type = _CONFIGURATIONPROPERTIES_AUDIOROUTINGPOLICY
_CONFIGURATIONPROPERTIES_AUDIOROUTINGPOLICY.containing_type = _CONFIGURATIONPROPERTIES
DESCRIPTOR.message_types_by_name['ConfigurationProperties'] = _CONFIGURATIONPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigurationProperties = _reflection.GeneratedProtocolMessageType('ConfigurationProperties', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONPROPERTIES,
  __module__ = 'Devialet.UnderTheBridge.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.UnderTheBridge.ConfigurationProperties)
  ))
_sym_db.RegisterMessage(ConfigurationProperties)



_CONFIGURATION = _descriptor.ServiceDescriptor(
  name='Configuration',
  full_name='Devialet.UnderTheBridge.Configuration',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\302>A\010\001\032$io.dvlt.underthebridge.configuration\"\027ConfigurationProperties'),
  serialized_start=420,
  serialized_end=505,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATION)

DESCRIPTOR.services_by_name['Configuration'] = _CONFIGURATION

# @@protoc_insertion_point(module_scope)
